# Generated by Django 4.2.1 on 2023-05-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('labelC', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('idComm', models.AutoField(primary_key=True, serialize=False)),
                ('nomComm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idEvent', models.AutoField(primary_key=True, serialize=False)),
                ('nomEvent', models.CharField(max_length=100)),
                ('descripEvent', models.CharField(max_length=1000)),
                ('dateEvent', models.DateField()),
                ('H_debut', models.TimeField()),
                ('H_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('idLieu', models.AutoField(primary_key=True, serialize=False)),
                ('nomLieu', models.CharField(max_length=100)),
                ('descripLieu', models.CharField(blank=True, max_length=1000)),
                ('exigence', models.CharField(blank=True, max_length=1000)),
                ('faitHisto', models.CharField(blank=True, max_length=1000)),
                ('produitArtis', models.CharField(blank=True, default='', max_length=1000)),
                ('expressCourantes', models.CharField(blank=True, max_length=1000)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('H_ouverture', models.TimeField(blank=True, null=True)),
                ('H_fermeture', models.TimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.categorie')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('idMeteo', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature', models.IntegerField()),
                ('prevision', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('idTheme', models.AutoField(primary_key=True, serialize=False)),
                ('labelT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('idTransport', models.AutoField(primary_key=True, serialize=False)),
                ('typeTrans', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nomUser', models.CharField(max_length=100)),
                ('prenomUser', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('motdepasse', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('numRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=100)),
                ('adminRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='static/images')),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_evotech.evenement')),
                ('lieuId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_evotech.lieu')),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.theme'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='id_lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
        migrations.AddField(
            model_name='commune',
            name='regionC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
    ]
