# Generated by Django 4.2.1 on 2023-05-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.AutoField(default='', primary_key=True, serialize=False)),
                ('labelC', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idEvent', models.AutoField(primary_key=True, serialize=False)),
                ('nomEvent', models.CharField(max_length=100)),
                ('descripEvent', models.CharField(max_length=1000)),
                ('dateEvent', models.DateField()),
                ('H_debut', models.TimeField()),
                ('H_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('idLieu', models.AutoField(primary_key=True, serialize=False)),
                ('nomLieu', models.CharField(max_length=100)),
                ('descripLieu', models.CharField(max_length=1000)),
                ('exigence', models.CharField(max_length=1000)),
                ('faitHisto', models.CharField(max_length=1000)),
                ('produitArtis', models.CharField(default='', max_length=1000)),
                ('expressCourantes', models.CharField(max_length=1000)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('H_ouverture', models.TimeField()),
                ('H_fermeture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('idMeteo', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature', models.IntegerField()),
                ('prevision', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('idTransport', models.AutoField(primary_key=True, serialize=False)),
                ('typeTrans', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('idTheme', models.AutoField(primary_key=True, serialize=False)),
                ('labelT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nomUser', models.CharField(max_length=100)),
                ('prenomUser', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('motdepasse', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('H_depart', models.TimeField()),
                ('id_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu')),
                ('id_moytrans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.moyentransport')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('numRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=100)),
                ('adminRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='adminRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='climat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.meteo'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='id_event',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.evenement'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('idComm', models.AutoField(primary_key=True, serialize=False)),
                ('nomComm', models.CharField(default='', max_length=100)),
                ('regionC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region')),
            ],
        ),
    ]
