# Generated by Django 4.2.1 on 2023-05-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='idCategorie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='labelC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='adminRegion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='climat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.meteo'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='id_event',
            field=models.ManyToManyField(blank=True, to='api_evotech.evenement'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='adminRegion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id_lieu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id_moytrans',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.moyentransport'),
        ),
    ]
