# Generated by Django 4.2.1 on 2023-06-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='idLieu',
        ),
        migrations.AddField(
            model_name='evenement',
            name='lieu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='feedback',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lieu',
            name='nmb_feedbach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='adminRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='climat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.meteo'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
    ]
