# Generated by Django 4.2.1 on 2023-06-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.transport'),
        ),
    ]
