# Generated by Django 4.2.1 on 2023-05-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='img')),
                ('lieuId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu')),
            ],
        ),
    ]
