# Generated by Django 4.2.1 on 2023-05-30 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='adminreg',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='evenement',
            name='Lieu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
