# Generated by Django 4.2.1 on 2023-06-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0002_remove_evenement_idlieu_evenement_lieu_lieu_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoris',
            old_name='idLieu',
            new_name='lieu',
        ),
    ]
