# Generated by Django 4.2.1 on 2023-05-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0002_alter_categorie_idcategorie_alter_categorie_labelc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='id_event',
        ),
        migrations.AddField(
            model_name='evenement',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='climat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.meteo'),
        ),
    ]
