# Generated by Django 4.2.1 on 2023-05-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0002_rename_user_notification_adminreg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='evenement',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='Lieu',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='event',
            new_name='lieu',
        ),
        migrations.AddField(
            model_name='lieu',
            name='feedback',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lieu',
            name='nmb_feedbach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='adminRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='climat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.meteo'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
    ]
