# Generated by Django 4.1.3 on 2023-06-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0003_historyevent_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLieu',
            fields=[
                ('idHis', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Type_Action', models.CharField(choices=[('Ajout lieu', 'Ajout lieu'), ('Modification lieu', 'Modification lieu'), ('Suppression lieu', 'Suppression lieu')], max_length=100)),
                ('Idlieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.evenement')),
                ('Iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
    ]
