# Generated by Django 4.2.1 on 2023-06-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0003_alter_lieu_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_evotech.evenement'),
        ),
    ]
