# Generated by Django 4.2.1 on 2023-05-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0004_alter_region_adminregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='lieu',
            new_name='lieu_id',
        ),
    ]
