# Generated by Django 4.2.1 on 2023-06-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0004_alter_photo_eventid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id_favoris', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
                ('id_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu')),
            ],
        ),
    ]
