# Generated by Django 4.2.1 on 2023-05-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0005_rename_lieu_evenement_lieu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='lieu_id',
            new_name='lieu',
        ),
    ]
