# Generated by Django 4.2.1 on 2023-06-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0005_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='feedback',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lieu',
            name='nmb_feedbach',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(default='', max_length=1000)),
                ('author', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('adminreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api_evotech.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_evotech.lieu')),
            ],
        ),
    ]
