# Generated by Django 4.2.1 on 2023-05-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='id_cat',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='idCategorie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
