# Generated by Django 4.2.1 on 2023-05-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0006_rename_lieu_id_evenement_lieu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ville',
            new_name='Commune',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='idVille',
            new_name='idCommune',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='nomVille',
            new_name='nomCommune',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='regionV',
            new_name='regionC',
        ),
    ]
