# Generated by Django 4.2.1 on 2023-06-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0006_lieu_feedback_lieu_nmb_feedbach_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='nmb_feedbach',
            new_name='nmb_feedback',
        ),
    ]
