# Generated by Django 4.2.1 on 2023-06-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0006_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
    ]
