# Generated by Django 4.2.1 on 2023-05-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0007_lieu_id_cat_alter_categorie_idcategorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='id_cat',
            new_name='categorie',
        ),
    ]
