# Generated by Django 4.2.1 on 2023-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0007_rename_nmb_feedbach_lieu_nmb_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coteRegion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
