# Generated by Django 4.2.1 on 2023-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0007_rename_nmb_feedbach_lieu_nmb_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='feedback',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='nmb_feedback',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
