# Generated by Django 4.2.1 on 2023-06-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0008_region_coteregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('idNotif', models.AutoField(primary_key=True, serialize=False)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLieu',
            fields=[
                ('idHis', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Type_Action', models.CharField(choices=[('Ajout lieu', 'Ajout lieu'), ('Modification lieu', 'Modification lieu'), ('Suppression lieu', 'Suppression lieu')], max_length=100)),
                ('Idlieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu')),
                ('Iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('idHis', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Type_Action', models.CharField(choices=[('Ajout Evenemen', 'Ajout Evenement'), ('Modification Evenement', 'Modification Evenement'), ('Suppression Evenement', 'Suppression Evenement'), ('Ajout lieu', 'Ajout lieu'), ('Modification lieu', 'Modification lieu'), ('Suppression lieu', 'Suppression lieu')], max_length=100)),
                ('Idevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.evenement')),
                ('Iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_evotech.user')),
            ],
        ),
    ]
