# Generated by Django 4.1.5 on 2023-05-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0008_remove_lieu_region_lieu_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='climat',
        ),
    ]
