# Generated by Django 4.2.1 on 2023-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0008_rename_id_cat_lieu_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.theme'),
        ),
    ]
