# Generated by Django 4.2.1 on 2023-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0008_alter_lieu_feedback_alter_lieu_nmb_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsArtis',
            fields=[
                ('idProduit', models.AutoField(primary_key=True, serialize=False)),
                ('nomProduit', models.CharField(default='', max_length=100)),
                ('prix', models.FloatField()),
            ],
        ),
    ]
