# Generated by Django 4.2.1 on 2023-06-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0009_notificationevent_historylieu_historyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='H_debut',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='H_fin',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateEvent',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='descripEvent',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nomEvent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
