# Generated by Django 4.2.1 on 2023-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0009_remove_lieu_climat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='H_depart',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='id_moytrans',
        ),
        migrations.AddField(
            model_name='transport',
            name='typeTrans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MoyenTransport',
        ),
    ]
