# Generated by Django 4.2.1 on 2023-05-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0009_lieu_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='adminRegion',
        ),
        migrations.AddField(
            model_name='lieu',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.commune'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nomComm',
            field=models.CharField(max_length=100),
        ),
    ]
