# Generated by Django 4.2.1 on 2023-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0009_produitsartis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='produits_artis',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.produitsartis'),
        ),
    ]
