# Generated by Django 4.2.1 on 2023-05-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0010_remove_transport_h_depart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='id_trans',
            new_name='idTransport',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='adminRegion',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='id_lieu',
        ),
        migrations.AddField(
            model_name='lieu',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.categorie'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.region'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.theme'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='transport',
            field=models.ManyToManyField(blank=True, to='api_evotech.transport'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='typeTrans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='static/images')),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_evotech.evenement')),
                ('lieuId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_evotech.lieu')),
            ],
        ),
    ]
