# Generated by Django 4.2.1 on 2023-05-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0010_remove_lieu_adminregion_lieu_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='id_event',
        ),
        migrations.AddField(
            model_name='evenement',
            name='id_lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_evotech.lieu'),
        ),
    ]
