# Generated by Django 4.2.1 on 2023-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0010_alter_evenement_h_debut_alter_evenement_h_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='H_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='H_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateEvent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
