# Generated by Django 4.2.1 on 2023-06-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0011_rename_id_trans_transport_idtransport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coteRegion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
