# Generated by Django 4.2.1 on 2023-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0011_alter_evenement_h_debut_alter_evenement_h_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='feedback',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='nmb_feedback',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
