# Generated by Django 4.2.1 on 2023-05-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0011_remove_lieu_id_event_evenement_id_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_evotech.lieu'),
        ),
    ]
