# Generated by Django 4.2.1 on 2023-06-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0013_alter_historyevent_idevent_alter_historyevent_iduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylieu',
            name='Idlieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_evotech.lieu'),
        ),
    ]
