# Generated by Django 4.2.1 on 2023-05-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0013_alter_photo_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyentransport',
            name='infosTrans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lieuId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_evotech.lieu'),
        ),
    ]
