# Generated by Django 4.2.1 on 2023-06-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0014_alter_historylieu_idlieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylieu',
            name='Idlieu',
            field=models.ForeignKey(default='ce lieu a été supprimé', on_delete=django.db.models.deletion.SET_DEFAULT, to='api_evotech.lieu'),
        ),
    ]
