# Generated by Django 4.2.1 on 2023-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0014_moyentransport_infostrans_alter_photo_lieuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='id_trans',
            new_name='idTransport',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='H_depart',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='id_lieu',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='id_moytrans',
        ),
        migrations.AddField(
            model_name='lieu',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.transport'),
        ),
        migrations.AddField(
            model_name='transport',
            name='typeTrans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='MoyenTransport',
        ),
    ]
