# Generated by Django 4.2.1 on 2023-05-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0015_rename_id_trans_transport_idtransport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='descripLieu',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='exigence',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='expressCourantes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='faitHisto',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='produitArtis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
