# Generated by Django 4.2.1 on 2023-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0016_alter_lieu_descriplieu_alter_lieu_exigence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='H_fermeture',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='H_ouverture',
            field=models.TimeField(blank=True),
        ),
    ]
