# Generated by Django 4.2.1 on 2023-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0017_alter_historyevent_idevent_alter_historyevent_iduser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
