# Generated by Django 4.2.1 on 2023-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0017_alter_lieu_h_fermeture_alter_lieu_h_ouverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='H_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='H_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
