# Generated by Django 4.2.2 on 2023-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0019_user_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsArtis',
            fields=[
                ('idProduit', models.AutoField(primary_key=True, serialize=False)),
                ('nomProduit', models.CharField(default='', max_length=100)),
                ('prix', models.FloatField()),
                ('origine', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='produits_artis',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.produitsartis'),
        ),
    ]
