# Generated by Django 4.2.1 on 2023-06-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0021_photo_produitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='produits_artis',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='produitId',
        ),
        migrations.DeleteModel(
            name='ProduitsArtis',
        ),
    ]
