# Generated by Django 4.2.1 on 2023-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0022_remove_lieu_produits_artis_remove_photo_produitid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsArtis',
            fields=[
                ('idProduit', models.AutoField(primary_key=True, serialize=False)),
                ('nomProduit', models.CharField(default='', max_length=100)),
                ('prix', models.FloatField()),
                ('origine', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
