# Generated by Django 4.2.1 on 2023-06-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0023_produitsartis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitsArtis',
        ),
    ]
