# Generated by Django 4.2.1 on 2023-06-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0024_delete_produitsartis'),
    ]

    operations = [
    ]
