# Generated by Django 4.2.1 on 2023-06-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_evotech', '0026_produitsartis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='produits_artis',
            field=models.ManyToManyField(blank=True, null=True, to='api_evotech.produitsartis'),
        ),
        migrations.AddField(
            model_name='photo',
            name='produitId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api_evotech.produitsartis'),
        ),
    ]
